# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.TextField(max_length=200)),
                ('LOR_contact', models.CharField(max_length=100)),
                ('ext_contact', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField()),
                ('materials_rec', models.TextField(max_length=200)),
                ('notes', models.TextField(max_length=500)),
                ('plans', models.TextField(max_length=500)),
            ],
        ),
    ]
