# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='LOR_contact',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='contact_date',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='ext_contact',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='materials_rec',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='website',
        ),
    ]
