# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-02 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor', '0002_auto_20170802_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='LOR_contact',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='friends',
            name='ext_contact',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='friends',
            name='materials_rec',
            field=models.TextField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='friends',
            name='notes',
            field=models.TextField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='friends',
            name='plans',
            field=models.TextField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='friends',
            name='website',
            field=models.TextField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
